Fix interface keyword build error on Windows
* interface is defined as struct on Windows
src/main.cpp:49:33: error: expected unqualified-id before 'struct'